### ISSUE TITLE
Update logging code

### ISSUE THREAD

**Issue by alepev** [thehyve/delphyne-template#12]
- [x] remove generic obsolete logging code
- ~ remove version logging in `main.py`?~ -> keep it as is for now, see comments below
- ~Add title lines to be able to easily distinguish different stages of the pipeline~ -> dropped the idea, could be done as needed by template user

I found and marked additional log messages in the template wrapper and main which could be integrated in the wrapper package.
Figure which ones are superfluous and which useful, and remove/refactor accordingly.

in `main.py`:
https://github.com/thehyve/ohdsi-etl-template/blob/d99b63f3cfe034ad84ad75bffd8708ee981e0245/main.py#L49-L54

in `wrapper.py`: (`run()`)
https://github.com/thehyve/ohdsi-etl-template/blob/d99b63f3cfe034ad84ad75bffd8708ee981e0245/src/main/python/wrapper.py#L54-L90

**Comment by alepev** [comment]
@MaximMoinat we were wondering about removing version logging in `main.py`. can you recall any project were the ETL version was ever updated to something else that `0.1.0`? :P 
https://github.com/thehyve/delphyne-template/blob/781e51b3248874ca71beecede6e6ef70bd59446a/main.py#L34

**Comment by MaximMoinat** [comment]
Yes, we certainly did.

The main purpose of logging the version is that we can later trace back what ETL has been run. Potentially very valuable when debugging any issues.

A better option is to automatically log the commit hash at which the ETL was run. (albeit that sometimes the data partner just downloads the code as a zip instead of doing a git clone)

**Comment by alepev** [comment]
We'll keep it as is for now, I'll make a new low-priority issue for the exact format of the version logging
